CREATE TABLE events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255)  NOT NULL,
    description      TEXT,
    organizer_name   VARCHAR(255)  NOT NULL,
    city             VARCHAR(20)   NOT NULL,
    category         VARCHAR(30)   NOT NULL,
    start_time       TIMESTAMP     NOT NULL,
    end_time         TIMESTAMP     NOT NULL,
    capacity         INT           NOT NULL,
    registered_count INT           NOT NULL DEFAULT 0,
    status           VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    thumbnail_path   VARCHAR(500),
    deleted_at       TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_events_city       CHECK (city IN ('HANOI', 'HCMC')),
    CONSTRAINT chk_events_category   CHECK (category IN ('TECHNOLOGY', 'SPORTS', 'EDUCATION', 'MUSIC')),
    CONSTRAINT chk_events_status     CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT chk_events_capacity   CHECK (capacity >= 0),
    CONSTRAINT chk_events_reg_count  CHECK (registered_count >= 0 AND registered_count <= capacity),
    CONSTRAINT chk_events_time_order CHECK (end_time > start_time)
);

CREATE INDEX idx_events_deleted_at   ON events (deleted_at);
CREATE INDEX idx_events_start_time   ON events (start_time);
CREATE INDEX idx_events_city         ON events (city);
CREATE INDEX idx_events_category     ON events (category);
CREATE INDEX idx_events_status       ON events (status);

CREATE INDEX idx_events_active_browse
    ON events (deleted_at, city, category, start_time);
