CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    event_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',

    registered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    cancelled_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_registrations_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_registrations_event
        FOREIGN KEY (event_id) REFERENCES events (id),

    CONSTRAINT uk_registrations_user_event
        UNIQUE (user_id, event_id),

    CONSTRAINT chk_registrations_status
        CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

CREATE INDEX idx_registrations_user_id ON registrations (user_id);
CREATE INDEX idx_registrations_event_id ON registrations (event_id);