spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/event_registration}
    username: ${DB_USERNAME:event}
    password: ${DB_PASSWORD:event123}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true